{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Tratando_Erros.ipynb","provenance":[],"authorship_tag":"ABX9TyPO4a4Py/TFBh/s151nnJ46"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["[Python Exception Handling Using *try*, *except* and *finally* statement.](https://www.programiz.com/python-programming/exception-handling)"],"metadata":{"id":"GmFapRsdc54G"}},{"cell_type":"code","execution_count":null,"metadata":{"id":"8wiok760c0RV"},"outputs":[],"source":[""]}]}